name: Prune messages and build feed


on:
schedule:
- cron: '*/5 * * * *' # run roughly every 5 minutes
push:
paths:
- 'data/messages/**' # also run whenever a message lands
workflow_dispatch:


permissions:
contents: write


jobs:
prune:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Use Node
uses: actions/setup-node@v4
with:
node-version: '20'
- name: Prune & build feed
run: node scripts/prune-and-build.js
- name: Commit changes
run: |
git config user.name "club72-bot"
git config user.email "bot@users.noreply.github.com"
git add -A
if ! git diff --cached --quiet; then
git commit -m "chore(feed): prune 24h+ & rebuild feed"
git push
fi